// Danh sách câu chúc hiển thị ngẫu nhiên trên màn hình chào sau khi đăng nhập (xem src/app/(auth)/login/page.tsx).
export const GREETING_QUOTES = [
  "Chúc bạn một ngày làm việc hiệu quả và nhiều năng lượng.",
  "Mỗi ngày là một cơ hội để tiến bộ hơn hôm qua.",
  "Hãy bắt đầu bằng một nhiệm vụ nhỏ, thành công sẽ đến tiếp theo.",
  "Chỉ cần tiến lên từng bước, bạn sẽ đến đích.",
  "Hôm nay là một ngày tuyệt vời để tạo nên giá trị.",
  "Mỗi việc hoàn thành đều góp phần vào thành công chung.",
  "Một khởi đầu tích cực sẽ tạo nên một ngày tích cực.",
  "Hãy bắt đầu với tinh thần vui vẻ và chủ động.",
  "Mỗi nỗ lực hôm nay đều có ý nghĩa.",
  "Chúc bạn có một ngày nhiều niềm vui và thành tựu.",
  "Hoàn thành từng nhiệm vụ nhỏ sẽ tạo nên thành công lớn.",
  "Một bước hôm nay tốt hơn mười bước ngày mai.",
  "Mỗi nhiệm vụ hoàn thành là một thành quả đáng ghi nhận.",
  "Hôm nay hãy cố gắng hơn hôm qua một chút.",
  "Một mầm cây được lớn lên nhờ bạn.",
  "Thành quả lớn bắt đầu từ những công việc nhỏ.",
  "Mỗi thao tác cẩn thận đều góp phần tạo nên chất lượng.",
  "Cẩn thận từng chi tiết sẽ tạo nên khác biệt.",
  "Hôm nay gieo sự tận tâm, ngày mai gặt thành quả.",
  "Mỗi cây khỏe mạnh đều bắt đầu từ một quy trình tốt.",
  "Chất lượng được tạo nên từ từng thao tác chính xác.",
  "Hãy để hôm nay là một ngày đầy sức sống.",
  "Bạn đang tiến gần mục tiêu hơn từng ngày.",
  "Kiên trì luôn tạo nên kết quả.",
  "Thành công là tổng của những nỗ lực nhỏ.",
  "Điều tuyệt vời sẽ đến với người không bỏ cuộc.",
  "Hãy làm hết khả năng của ngày hôm nay.",
  "Không cần hoàn hảo, chỉ cần tiến bộ.",
  "Mỗi ngày đều đáng để cố gắng.",
  "Bạn có thể làm nhiều hơn mình nghĩ.",
  "Hãy tin vào giá trị của sự kiên trì.",
  "Hãy làm việc với niềm tự hào.",
  "Một thái độ tích cực sẽ tạo nên kết quả tích cực.",
  "Chất lượng luôn được ghi nhận.",
  "Công việc hôm nay là nền tảng của ngày mai.",
  "Thành công được xây từ những điều nhỏ nhất.",
  "Luôn có cơ hội để làm tốt hơn.",
  "Mỗi người đều tạo nên giá trị cho tập thể.",
  "Hãy để hôm nay trở thành một ngày đáng nhớ.",
  "Nỗ lực của bạn luôn có ý nghĩa.",
  "Hãy làm việc với tinh thần tích cực.",
  "Hôm nay là cơ hội mới.",
  "Bắt đầu với nụ cười.",
  "Hãy lan tỏa năng lượng tích cực.",
  "Mỗi ngày đều có điều đáng mong đợi.",
  "Một ngày tốt bắt đầu từ một suy nghĩ tích cực.",
  "Hãy chủ động tạo nên thành công.",
  "Luôn giữ tinh thần học hỏi.",
  "Thành quả sẽ đến với người kiên trì.",
  "Chúc bạn có một ngày thật hiệu quả.",
  "Hãy làm việc bằng cả sự tận tâm.",
  "Cùng nhau sẽ đi xa hơn.",
  "Mỗi người đều là một phần quan trọng của tập thể.",
  "Chia sẻ sẽ tạo nên sức mạnh.",
  "Hãy giúp đỡ nhau khi cần.",
  "Thành công của tập thể bắt đầu từ từng cá nhân.",
  "Một lời động viên có thể thay đổi cả ngày làm việc.",
  "Cùng nhau tạo nên một ngày thật hiệu quả.",
  "Mỗi nhiệm vụ hoàn thành đều đáng tự hào.",
  "Tiến bộ nhỏ mỗi ngày tạo nên thành công lớn.",
  "Hãy ghi nhận những gì bạn đã làm được.",
  "Mỗi bước tiến đều có giá trị.",
  "Bạn đang làm rất tốt.",
  "Hãy tiếp tục phát huy.",
  "Cố gắng hôm nay sẽ được đền đáp.",
  "Thành công đến từ sự bền bỉ.",
  "Hôm nay hãy vượt qua chính mình.",
  "Hãy tự hào về những nỗ lực của mình.",
  "Bình tĩnh, tập trung và từng bước hoàn thành.",
  "Một ngày tốt đẹp đang chờ bạn.",
  "Hãy tận hưởng công việc của mình.",
  "Luôn giữ tinh thần lạc quan.",
  "Nụ cười giúp công việc nhẹ nhàng hơn.",
  "Điều tốt đẹp bắt đầu từ hôm nay.",
  "Hãy để năng lượng tích cực dẫn lối.",
  "Chúc bạn một ngày thật nhiều cảm hứng.",
  "Mỗi ngày đều có cơ hội để học hỏi.",
  "Hãy tạo nên những điều tuyệt vời.",
  "Hôm nay là một ngày đáng để cố gắng.",
  "Hãy tin vào chính mình.",
  "Thành công bắt đầu từ hành động.",
  "Đừng ngại thử thách.",
  "Kiên trì sẽ đưa bạn đến đích.",
  "Hãy hoàn thành từng mục tiêu nhỏ.",
  "Chúc bạn có một ngày làm việc trọn vẹn.",
  "Cảm ơn vì những nỗ lực của bạn.",
  "Chúng ta cùng tạo nên những giá trị tốt đẹp.",
  "Chúc bạn một ngày làm việc vui vẻ, hiệu quả và đầy năng lượng!",
] as const;

export function randomGreetingQuote(): string {
  return GREETING_QUOTES[Math.floor(Math.random() * GREETING_QUOTES.length)];
}

// 30 nền gradient ngẫu nhiên cho màn hình chào sau khi đăng nhập — chỉ dùng token màu có sẵn trong
// theme (globals.css), không dùng ảnh, nên không tốn thêm dung lượng tải hay ảnh hưởng hiệu năng.
export const GREETING_BACKGROUNDS = [
  "bg-gradient-to-br from-primary-bg to-primary-light",
  "bg-gradient-to-tr from-primary-light to-success-light",
  "bg-gradient-to-bl from-info-light to-primary-bg",
  "bg-gradient-to-tl from-violet-light to-primary-light",
  "bg-gradient-to-r from-primary-bg to-info-light",
  "bg-gradient-to-b from-success-light to-primary-bg",
  "bg-gradient-to-br from-warning-light to-primary-bg",
  "bg-gradient-to-tr from-achievement/15 to-primary-light",
  "bg-gradient-to-bl from-primary-bg via-primary-light to-info-light",
  "bg-gradient-to-tl from-violet-light via-primary-bg to-success-light",
  "bg-gradient-to-r from-info-light via-primary-light to-violet-light",
  "bg-gradient-to-b from-primary-light via-success-light to-primary-bg",
  "bg-gradient-to-br from-secondary/20 to-primary-light",
  "bg-gradient-to-tr from-primary-bg to-warning-light",
  "bg-gradient-to-bl from-success-light via-primary-bg to-violet-light",
  "bg-gradient-to-tl from-info-light to-success-light",
  "bg-gradient-to-r from-violet-light to-primary-bg",
  "bg-gradient-to-b from-warning-light via-primary-light to-info-light",
  "bg-gradient-to-br from-primary-light to-violet-light",
  "bg-gradient-to-tr from-success-light via-info-light to-primary-bg",
  "bg-gradient-to-bl from-primary-bg to-achievement/15",
  "bg-gradient-to-tl from-primary-light via-warning-light to-primary-bg",
  "bg-gradient-to-r from-primary-bg via-violet-light to-info-light",
  "bg-gradient-to-b from-info-light to-primary-light",
  "bg-gradient-to-br from-primary-bg via-success-light to-violet-light",
  "bg-gradient-to-tr from-violet-light to-warning-light",
  "bg-gradient-to-bl from-primary-light to-info-light",
  "bg-gradient-to-tl from-success-light to-warning-light",
  "bg-gradient-to-r from-primary-bg via-info-light to-primary-light",
  "bg-gradient-to-b from-violet-light via-primary-bg to-success-light",
  "bg-gradient-to-l from-primary-bg to-success-light",
  "bg-gradient-to-t from-info-light to-violet-light",
  "bg-gradient-to-br from-muted to-primary-light",
  "bg-gradient-to-tr from-primary-bg to-accent",
  "bg-gradient-to-bl from-accent to-info-light",
  "bg-gradient-to-tl from-muted to-success-light",
  "bg-gradient-to-r from-success-light to-violet-light",
  "bg-gradient-to-b from-primary-bg to-violet-light",
  "bg-gradient-to-l from-warning-light to-violet-light",
  "bg-gradient-to-t from-primary-light to-primary-bg",
  "bg-gradient-to-br from-info-light via-primary-bg to-warning-light",
  "bg-gradient-to-tr from-violet-light via-success-light to-primary-bg",
  "bg-gradient-to-bl from-warning-light via-primary-light to-success-light",
  "bg-gradient-to-tl from-primary-bg via-info-light to-violet-light",
  "bg-gradient-to-r from-achievement/15 via-primary-bg to-success-light",
  "bg-gradient-to-b from-secondary/15 via-primary-light to-info-light",
  "bg-gradient-to-l from-primary-light via-violet-light to-primary-bg",
  "bg-gradient-to-t from-success-light via-primary-bg to-warning-light",
  "bg-gradient-to-br from-primary-bg to-muted",
  "bg-gradient-to-tr from-info-light to-primary-bg",
  "bg-gradient-to-bl from-violet-light to-warning-light",
  "bg-gradient-to-tl from-success-light to-primary-light",
  "bg-gradient-to-r from-warning-light to-primary-light",
  "bg-gradient-to-b from-accent to-primary-bg",
  "bg-gradient-to-l from-info-light to-success-light",
  "bg-gradient-to-t from-violet-light to-info-light",
  "bg-gradient-to-br from-success-light via-violet-light to-info-light",
  "bg-gradient-to-tr from-warning-light via-achievement/15 to-primary-bg",
  "bg-gradient-to-bl from-primary-light via-primary-bg to-warning-light",
  "bg-gradient-to-tl from-violet-light via-info-light to-success-light",
] as const;

export function randomGreetingBackground(): string {
  return GREETING_BACKGROUNDS[Math.floor(Math.random() * GREETING_BACKGROUNDS.length)];
}
